#!/bin/bash
# -----------------------------------------
# - Gestionnaire de certifications        -
# - (c) Libre En Poche                    -
# - Licence GPL-v3 (voir fichier licence) -
# -----------------------------------------

. ./functions.inc

loadConfig
echoName

function usage () {
    echo -e "$0 subdomain\n"
    exit 1
}

if [ $# -ne 1 ]
then
    usage
fi

SUBDOMAIN=$1
SUBDIR=${SUBDOMAINSCRTDIR}/${SUBDOMAIN}
OUSD=subdomain-${SUBDOMAIN}

testIfRootCert
testIfSubdomainCert ${SUBDOMAIN}
testIfCertSubRevoked ${SUBDOMAIN}

revoke () {
    TYPE=$1
    S="${SUBDIR}/certs/${TYPE}-${SUBDOMAIN}-"
    SL=${#S}
    echo -n "${TYPE}s : "
    for i in `ls ${S}*.pem 2>/dev/null`
    do
        NAME="${i:$SL:-4}"
        grep "${TYPE}-${SUBDOMAIN}-${NAME}$" ${SUBDIR}/index.txt | grep "^V" > /dev/null
        if [ $? -eq 0 ]
        then
            echo -n "+${NAME} "
            ./revokecs ${TYPE} ${SUBDOMAIN} ${NAME} >/dev/null 2>&1
        else
            echo -n "-${NAME} "
        fi
    done
    echo
}

echo -e "\nRevocation du sous-domaine ${SUBDOMAIN}..."

echo "** Revocation des serveurs et clients du sous-domaine..."

revoke server
revoke client

echo "** Revocation du certificat..."

openssl ca \
    -config ${ROOTCRTDIR}/openssl.conf \
    -passin file:${ROOTCRTDIR}/.passwd \
    -revoke \
    ${SUBDIR}/certs/subdomain-${SUBDOMAIN}.pem \
    > /dev/null 2>&1

echo "** Regeneration du certificat de revocation..."

openssl ca \
    -config ${ROOTCRTDIR}/openssl.conf \
    -passin file:${ROOTCRTDIR}/.passwd \
    -gencrl \
    -keyfile ${ROOTCRTDIR}/private/root_ca.key \
    -cert ${ROOTCRTDIR}/certs/root_ca.pem \
    -crldays 3650 \
    -out ${ROOTCRTDIR}/revoked.crl \
    > /dev/null 2>&1

# on peut se contenter du sous-domaine mais, par coherence, on refait tout
# a commencer par le sous domaine qui sera exclu de la boucle (car rrevoque)
cp ${ROOTCRTDIR}/revoked.crl ${TRUSTEDANDCRLDIR}/${SUBDOMAIN}.crl
cat ${SUBDIR}/revoked.crl >> ${TRUSTEDANDCRLDIR}/${SUBDOMAIN}.crl
echo -n "Sous-domaine: "
cd ${SUBDOMAINSCRTDIR}
for i in `find * -maxdepth 0 -type d`
do
    if [ -f ${i}/revoked.crl ]
    then
        grep "CN=subdomain-${i}$" ${ROOTCRTDIR}/index.txt | grep "^V" > /dev/null
        if [ $? -eq 0 ]
        then
            echo -n "+${i} "
        else
            echo -n "-${i} "
        fi
        cp ${ROOTCRTDIR}/revoked.crl ${TRUSTEDANDCRLDIR}/${i}.crl
        cat ${i}/revoked.crl >> ${TRUSTEDANDCRLDIR}/${i}.crl
    fi
done
echo

echo "** Prise en compte par NGINX..."
service nginx reload

echo -e "\nCertificat revoque.\n"

